#pragma once

#include "registers.hh"
#include "registers-internal.hh"

namespace hal {
namespace arm {
namespace stm32l0538 {

MCU_DECLARE_REGISTER(TIMER6, arm::TIMERX);
MCU_DECLARE_REGISTER(PWR_CR, arm::PWR_CR);
MCU_DECLARE_REGISTER(EXTI, arm::EXTI);
MCU_DECLARE_REGISTER(SPI1, arm::SPI);
MCU_DECLARE_REGISTER(SPI2, arm::SPI);
MCU_DECLARE_REGISTER(USART1, arm::USART);
MCU_DECLARE_REGISTER(DBG_APB1_FREEZE, arm::APB1);
MCU_DECLARE_REGISTER(RCC, arm::RCC);
MCU_DECLARE_REGISTER(DMA, arm::DMA);
MCU_DECLARE_REGISTER(GPIO_A, arm::GPIO);
MCU_DECLARE_REGISTER(GPIO_B, arm::GPIO);
MCU_DECLARE_REGISTER(NVIC, arm::NVIC);
MCU_DECLARE_REGISTER(MPU, arm::MPU);
MCU_DECLARE_REGISTER(SCB, arm::SCB);

}
}
}
